(in-package :star.app)

(defclass editor-app (star-app)
  ((documents :initform (make-hash-table :test #'equal) :accessor editor-documents)
   (dataset :type string :initform "" :accessor editor-default-dataset)))
(defmethod add-document ((app editor-app) document)
  (setf (gethash (spec:doc-id document) (editor-documents app)) document))
(defvar *editor-app* (make-instance 'editor-app :client (api-client *app*) :app-name "Document Editor"))

(defun create-document-type-select (container)
  (let ((select (create-select container :class "form-select")))
    (dolist (type *document-types*)
      (create-option select :content (car type) :value (car type)))
    select))

(defun on-document-editor (body)
  (on-page body "Document Editor")
  (let* ((container (create-div body :class "container"))
         (type-select (create-document-type-select container))
         (form-container (create-div container))
         (doc-grid (create-div container :class "columns")))
    (labels ((update-form ()
               (setf (inner-html form-container) "")
               (create-document-form form-container (value type-select) nil t
                 (lambda (document)
                   (add-document *editor-app* document)
                   (create-document-card doc-grid document)))))
      (update-form)
      (set-on-change type-select (lambda (obj) (declare (ignore obj)) (update-form))))
    (run body)))
